export const GET_MAINBOARDS_LIST = "GET_MAINBOARDS_LIST";

export const GET_RELATED_SENSORS = "GET_RELATED_SENSORS";

export const GET_SENSOR_TYPES = "GET_SENSOR_TYPES";

export const SAVE_MAINBOARD_ID = "SAVE_MAINBOARD_ID";

export const REGISTER_SENSOR_TYPE = "REGISTER_SENSOR_TYPE";

export const GET_SENSOR_VALUE_ITEM = "GET_SENSOR_VALUE_ITEM";

export const GET_ERRORS = "GET_ERRORS";

export const CREATE_MESSAGE = "CREATE_MESSAGE";

export const CHANGE_SEARCH_FIELD = "CHANGE_SEARCH_FIELD";

export const USER_LOADING = "USER_LOADING";

export const USER_LOADED = "USER_LOADED";

export const AUTH_ERROR = "AUTH_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const REGISTER_MAINBOARD_SUCCESS = "REGISTER_MAINBOARD_SUCCESS";

export const REGISTER_MAINBOARD_FAIL = "REGISTER_FAIL";
