export const GET_MAINBOARDS_LIST = "GET_MAINBOARDS_LIST";
export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const GET_MESSAGE = "GET_MESSAGE";

export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';
