# Generated by Django 3.1.4 on 2021-01-09 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainBoard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('mainboard_user', models.OneToOneField(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='main_board', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('mainboard_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mbapi.mainboard')),
            ],
        ),
        migrations.CreateModel(
            name='SensorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SensorValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('value', models.FloatField()),
                ('mainboard_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mbapi.mainboard')),
                ('sensor_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mbapi.sensors')),
            ],
        ),
        migrations.AddField(
            model_name='sensors',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mbapi.sensortype'),
        ),
    ]
