# Generated by Django 3.1.4 on 2021-01-21 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorvalue',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
