# Generated by Django 3.1.4 on 2021-01-03 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mbapi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
