# Generated by Django 3.1.4 on 2021-02-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbapi', '0002_auto_20210121_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensortype',
            name='description',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
